### ISSUE TITLE
How to resolve nested structures.

### ISSUE THREAD

**Issue by yiippee** [bbuck/go-lexer#5]
Thanks for your repo.
I see the code source, but I do not know how to resolve nested structures. Or maybe the lexer does not support?
for example: ( aaaa(bbbb)cccc ),  I want to get the tokens splited by bracket
Can you show something? Thanks again.

**Comment by bbuck** [comment]
I'm not 100% sure what you're asking for here, if you just want to split the string on some basic pattern then a lexer is way more than you need, just use `regexp` (https://play.golang.org/p/6eRmTffzgI-).

But if you really wanted to lex that, I would imagine the desired token output to be: `['(', 'aaaa', '(', 'bbbb', ')', 'cccc', ')']` and you wouldn't consider anything "nested" during the lexical analysis but instead deal with that when you're parsing the tokens into meaningful structures.

**Comment by yiippee** [comment]
Thank you very much for your reply. I am a Chinese student, and sorry for my poor English.
You said "you wouldn't consider anything "nested" during the lexical analysis but instead deal with that when you're parsing the tokens into meaningful structures.",  But sometimes consider "nested" is useful. for example I want to get the token between "( )", so when meet '(' I know this is where it starts, then get the word until meet ')', finally emit the token.Like a recursive descent parser. But in your go-lexer when emit a token, it will clear the stack.Maybe now it has not yet finished parsed because it is a nested structure.
Or I misunderstand something? Looking forward your reply. Thanks a lot.

**Comment by bbuck** [comment]
> you wouldn't consider anything "nested" during the lexical analysis

Typically, the lexer doesn't need any context to identify tokens. For example in a programming language the lexer doesn't need to know if it's parsing a variable name or a method name or if the variable is in a parameter list or being assigned to, etc... it just cares that "I see an identifier and it's not a keyword." This means that while you break your string into meaningful units you don't really want to, or need to, keep context about you've already seen. You're converting bytes into meaningful tokens and the parser will assign meaning (in this case, depth) to the tokens.

```
"("     <- At this point, your parser would notice a group has started
"aaaa"  <- Then of course, there is an identifier
"("     <- Once again, the parser notices a group is started and is already aware (or not, depending on implementation) that it's in a group
"bbbb"  <- Now the nested item
")"     <- A group has closed (the 'bbbb' group)
"cccc"  <- Back to parsing original data
")"     <- And finally the opening group has closed
        <- Typically an EOF token denotes "no more"
```

Without any real understanding of your use case, your parser might produce some output like:

```go
nodes := []Node{
        Group{
                Identifier("aaaa"),
                Group{
                        Identifier("bbbb"),
                },
                Identifier("cccc"),
        },
}
```

(sample of that structure producing your input here: https://play.golang.org/p/m3syYuvhJBs)

So again, you'd start with the input "( aaaa(bbbb)cccc )" and then lex it (maybe using this library) to get a set of tokens, maybe like this: `[]string{"(", "aaaa", "(", "bbbb", ")", "cccc", ")"}`. Once you have that you feed into your parser and your parser will produce (maybe) an array of nodes from which you can analyze your input like you want. For example, how many groups were at the top level? Just `len(nodes)`. Where there any nested groups in that example? Just iterate the children of the first group and count how many groups you see. Without more detail about what you're trying to do or what kind of output you want I can't be more specific.
